package ru.ezhov.featuretoggles.featuretoggle.interfaces.rest.v1.model

class InputConditionParametersConfigurationResponseDto(val inputParameters: List<InputConditionParameterConfigurationResponseDto>)