package ru.ezhov.featuretoggles.featuretoggle.interfaces.rest.v1.model

class InputConditionParametersConfigurationRequestDto(val inputParameters: List<InputConditionParameterConfigurationRequestDto>)